### ISSUE TITLE
Generating with duplicate name in different wsdl files

### ISSUE THREAD

**Issue by jmattheis** [dmak/jaxb-xew-plugin#44] opened 2015-11-24 13:23 UTC
Hey again,
I'm trying to generate the wsclient in the same directory with different wsdl's
The only problem is now that there are duplicate names.
In my example there is in ``test.wsdl`` the ``string2string2ArrayOfStringMapMap`` which has entries and a ``string2ArrayOfStringMap`` which has a different entry but with the same name, this all generating well.
The is an ``Entry.java`` which has ``List<String2ArrayOfStringMapEntry>`` and there is an ``String2ArrayOfStringMapEntry`` which has ``List<String>`` thats all correct but when I now generating the wsdl file with the second wsdl which doesn't have ``string2string2ArrayOfStringMapMap``.
Its generating ``Entry.java`` again but then instead of ``List<String2ArrayOfStringMapEntry>`` with ``List<String>`` which will make ``String2ArrayOfStringMapEntry`` == ``Entry`` so the *Entry with ``List<String2ArrayOfStringMapEntry>`` is missing because the old ``Entry`` got overwritten.
Without the xew plugin it generates the entry ``String2ArrayOfStringMap.Entry`` or ``String2string2ArrayOfStringMapMap.Entry`` so I guess this is because of xew.

So is there the possibility to not generate Entry but rather generate for ``String2ArrayOfStringMap.Entry`` ``String2ArrayOfStringMapEntry`` and so on that there is no single ``Entry`` class?

https://github.com/jmattheis/jaxb-xew-plugin/tree/master/samples/cxf-codegen-plugin-other

EDIT: The String2*Map have as key String and in my text I'm mean the value

**Comment by jmattheis** [comment] 2015-11-30 12:31
So the fix for this would be: to remove that if block in https://github.com/dmak/jaxb-xew-plugin/blob/master/src/main/java/com/sun/tools/xjc/addon/xew/XmlElementWrapperPlugin.java#L1121
I would suggest to add some configuration parameter for this.

**Comment by dmak** [comment] 2015-11-30 19:11
There is certainly a problem there, but the solution that you suggest does not work, as it breaks one unit test. Actually the intended behaviour in line 1121 is right (as it prevents the collision of `String2ArrayOfStringMap.Entry` and `String2String2ArrayOfStringMapMap.Entry` when those are moved to package), the error is in some other place.

**Comment by dmak** [comment] 2015-11-30 19:18
OK, I got why I was confused. In your code generation cycle you used two WSDL files (`test.wsdl` and `test2.wsdl`), and the 2nd one was partially overwriting the 1st one. Could you tell me, which of two I should focus on? I have checked `test.wsdl` (specified `<include>test.wsdl</include>` in `pom.xml`) and the result just looks fine. I don't understand your confusion relating to `List<String2ArrayOfStringMapEntry>`, because `string2string2ArrayOfStringMapMap` type is not part of `test2.wsdl`. You need to choose one specific WSDL and do `mvn clean install` to have a clean run.

**Comment by jmattheis** [comment] 2015-11-30 19:34
"String2ArrayOfStringMap.Entry and String2String2ArrayOfStringMapMap.Entry when those are moved to package), the error is in some other place."
What i trying to achieve that there is no singe ``Entry`` class that they have the classname from the removed wrapper class within the name so ``String2String2ArrayOfStringMapMap.Entry`` goes to ``String2String2ArrayOfStringMapMapEntry`` which the plugin already does when the ``Entry`` class is already set.
The problem with the current plugin is that i have wsdl's with different objects in it which have this ``Entry`` class which gets overwritten from other wsdl's

**Comment by jmattheis** [comment] 2015-12-01 07:18
So I may write a example again:
1 wsdl
```
String2StringMap
    with Entry
String2ArrayOfStringMap
    with Entry
```
2 wsdl
```
String2ArrayOfStringMap
    with Entry
String2OtherMap
    with Entry
```
in both wsdl there are duplicate objects 
Objects generated from wsdl:
1. run
```
Entry (from String2StringMap)
String2ArrayOfStringMapEntry (from String2ArrayOfStringMap)
```
when I now generate the second wsdl in the client, there are duplicate types but not all are duplicate and some are missing so the objects from the 2. wsdl generation
```
Entry (from String2ArrayOfStringMap)
String2OtherMapEntry (from String2OtherMap)
```
The file would be generated in the same folder so the Entry from the 2. run would overwrite the Entry from the 1. run
So the files would be:
```
Entry (from String2ArrayOfStringMap)
String2OtherMapEntry (from String2OtherMap)
String2ArrayOfStringMapEntry (from String2ArrayOfStringMap)
```
So my fix would be that classes which are in classes should always be named like ``classname from class wrapper`` + ``classname from inner class`` that as in my example there is no single ``Entry`` class

**Comment by dmak** [comment] 2015-12-01 14:26
I understand the "problem". Actually, it is not bounded to Xew plugin, as you can see. The thing is that it reveals when you start using Xew plugin. The common approach is to use separate packages for different WSDL files. You may agree that if the two WSDL files contain top-level types with the same name, they will collide.
So, to workaround the "problem" you should use JAXB customizations. For example, in `test2.wsdl` you can say something like that:
```
<xsd:complexType name="String2ArrayOfStringMap">
	<xsd:sequence>
		<xsd:element maxOccurs="unbounded" minOccurs="0" name="entry">
			<xsd:complexType>
				<xsd:annotation>
					<xsd:appinfo>
						<jaxb:class name="MyEntry" />
					</xsd:appinfo>
				</xsd:annotation>
				<xsd:sequence>
					<xsd:element maxOccurs="1" minOccurs="0" name="key" type="xsd:string"/>
					<xsd:element maxOccurs="1" minOccurs="0" name="value" type="tns:ArrayOfString"/>
				</xsd:sequence>
			</xsd:complexType>
		</xsd:element>
	</xsd:sequence>
</xsd:complexType>
```
(also add `xmlns:jaxb="http://java.sun.com/xml/ns/jaxb"` to the root tag). Now the 2nd `Entry` will become `MyEntry` and will not collide with type from `test.wsdl`.
P.S. I can find a bad example for your "fix", i.e. the test case when it will also "fail". There is no clean solution for the problem, except to use different packages for different compilations.

**Comment by jmattheis** [comment] 2015-12-02 08:13
Well, I cannot edit the wsdl, so I may just build a custom jar from your project with my "fixes" as I see no other option. Can be closed then.

**Comment by dmak** [comment] 2015-12-02 10:42
JAXB customizations can be applied using the external file. You already have `jaxbBindings.xml` in root of the project – you just need to extend it. Read on the Web about the format of this file (this is out of scope for Xew plugin).

**Closed by dmak** 2015-12-02 10:42 UTC

**Comment by jmattheis** [comment] 2016-03-11 06:38
With the suggested "fix" above, it all works fine for me. It does not kill my ObjectFactories because classes in other wsdl's are generated in an other package, and the duplicated once which are in the same package, are present in all wsdl.
